### ISSUE TITLE
How to run benchmarks for ng-tasty

### ISSUE THREAD

**Issue by skusunam** [Zizzamia/ng-tasty#125]
Here is what i did and still not able to run the benchmarks:

1) Went to an empty folder and executed this:
`> npm install benchpress ng-tasty`

2) Then executed these:
> npm install -g generator-benchpress
> yo benchpress ng-tasty

3) After jumping through few hoops i was able to run with the following command:
> protractor benchmarks/protractorBenchmarks.conf.js 

Output:
```
Using ChromeDriver directly...
[launcher] Running 1 instances of WebDriver
Starting up http-server, serving ./ on: http://localhos:8080
Started
A Jasmine spec timed out. Resetting the WebDriver Control Flow.
F

Failures:
1) deep tree baseline should work caseOne
  Message:
    Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
  Stack:
    Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
        at Timer.listOnTimeout [as ontimeout] (timers.js:112:15)

1 spec, 1 failure
Finished in 30.01 seconds
[launcher] 0 instance(s) of WebDriver still running
[launcher] chrome #1 failed 1 test(s)
[launcher] overall: 1 failed spec(s)
[launcher] Process exited with error code 1
```
Not sure what i am missing. If i try to run any of the `benchmarks` inside `ng-tasty` i get same error. I must be missing something?

**Comment by skusunam** [comment]
I was able to run with some changes to 'protractorBenchmarks.conf.js" which is generated after "yo benchpress ng-tasty". I wish we can run these right after they generated without any changes. Also we need little more clear documentation on how to run these benchmark tests.

Thanks for putting this as this really helping me on how to setup benchmarks on our own internal "grid" implementation. After this planning to use similar benchmarks for every internal widget with in the enterprise. Let me know if i can help anyway?

**Comment by Zizzamia** [comment]
I follow your steps
```
mkdir leo
cd leo
npm install -g generator-benchpress
yo benchpress ng-tasty
protractor benchmarks/protractorBenchmarks.conf.js
```

And I get this error
```
ERROR - failed loading configuration file benchmarks/protractorBenchmarks.conf.js
...
Error: Cannot find module 'http-server'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/lzizzamia/Desktop/leo/benchmarks/protractorBenchmarks.conf.js:1:80)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```

So I install the missing dependency 
```
npm install http-server
```
And run again `protractor benchmarks/protractorBenchmarks.conf.js` everything worked correctly
```
Using ChromeDriver directly...
[launcher] Running 1 instances of WebDriver
Starting up http-server, serving ./ on: http://localhos:8080
Started
BENCHMARK ngtasty.caseOne
Description:
- forceGc: false
- regressionSlopeMetric: scriptTime
- sampleSize: 10
- tree: baseline
- userAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.118 Safari/537.36
Metrics:
- gcAmount: gc amount in kbytes
- gcTime: gc time in and ouside of script in ms
- majorGcTime: time of major gcs in ms
- pureScriptTime: script execution time in ms, without gc nor render
- renderTime: render time in and ouside of script in ms
- scriptTime: script execution time in ms, including gc and render

          gcAmount |             gcTime |        majorGcTime |     pureScriptTime |         renderTime |         scriptTime
------------------ | ------------------ | ------------------ | ------------------ | ------------------ | ------------------
            493.96 |               1.25 |               0.00 |              12.03 |               9.30 |              12.03
              0.00 |               0.00 |               0.00 |               3.02 |               8.52 |               3.02
            947.36 |               1.65 |               0.00 |               2.86 |               7.70 |               2.86
              0.00 |               0.00 |               0.00 |               1.38 |               7.10 |               1.38
            750.30 |               2.45 |               0.00 |               1.92 |               9.19 |               1.92
              0.00 |               0.00 |               0.00 |               1.41 |               7.48 |               1.41
              0.00 |               0.00 |               0.00 |               1.41 |               8.22 |               1.41
            920.84 |               1.63 |               0.00 |               1.72 |               7.57 |               1.72
              0.00 |               0.00 |               0.00 |               1.40 |               8.04 |               1.40
              0.00 |               0.00 |               0.00 |               1.54 |               7.75 |               1.54
              0.00 |               0.00 |               0.00 |               1.98 |               8.19 |               1.98
              0.00 |               0.00 |               0.00 |               1.66 |               7.43 |               1.66
              0.00 |               0.00 |               0.00 |               1.57 |               7.57 |               1.57
================== | ================== | ================== | ================== | ================== | ==================
      167.11+-201% |         0.41+-205% |         0.00+-NaN% |          1.60+-12% |           7.85+-7% |          1.60+-12%
.


1 spec, 0 failures
Finished in 5.199 seconds
[launcher] 0 instance(s) of WebDriver still running
[launcher] chrome #1 passed
```
@skusunam thank you for your feedback, we totally need a better documentation about it.
What you did change on `protractorBenchmarks.conf.js` ?

**Comment by skusunam** [comment]
I had to run "npm install benchpress" on top of your steps.

Also noticed that 8080 port was used by some other process on my Mac and i was getting "page not available" error. I can run now without any changes to configuration file. Thank You !!!!

**Comment by Zizzamia** [comment]
Awesome! Do you want help me write a `.md` file to document better the Benchpress steps?
